// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_KeyboardCorrector_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::KeyboardCorrector::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::KeyboardCorrector
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<KeyboardCorrector::implementation::XamlMetaDataProvider>())
    {
    }
}
