// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_0_H
#define WINRT_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_0_H
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct HResult;
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime
{
    enum class DeploymentStatus : int32_t
    {
        Unknown = 0,
        Ok = 1,
        PackageInstallRequired = 2,
        PackageInstallFailed = 3,
    };
    struct IDeploymentManagerStatics;
    struct IDeploymentResult;
    struct IDeploymentResultFactory;
    struct DeploymentManager;
    struct DeploymentResult;
}
namespace winrt::impl
{
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResultFactory>{ using type = interface_category; };
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentManager>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult>{ using type = class_category; };
    template <> struct category<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentStatus>{ using type = enum_category; };
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentManager> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentStatus> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentStatus";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentResult";
    template <> inline constexpr auto& name_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResultFactory> = L"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentResultFactory";
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics>{ 0x6782A9D0,0xBFD0,0x50EA,{ 0x81,0xB0,0x32,0xE9,0xED,0x37,0xCD,0xF0 } }; // 6782A9D0-BFD0-50EA-81B0-32E9ED37CDF0
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult>{ 0x27203F62,0x463D,0x587A,{ 0x8E,0xB7,0x87,0x00,0x98,0x90,0x10,0x78 } }; // 27203F62-463D-587A-8EB7-870098901078
    template <> inline constexpr guid guid_v<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResultFactory>{ 0xACD7BDAE,0x4AE6,0x5CAC,{ 0x82,0x05,0x1E,0x8C,0x30,0x5F,0x95,0x3B } }; // ACD7BDAE-4AE6-5CAC-8205-1E8C305F953B
    template <> struct default_interface<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult>{ using type = winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult; };
    template <> struct abi<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall GetStatus(void**) noexcept = 0;
            virtual int32_t __stdcall Initialize(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_Status(int32_t*) noexcept = 0;
            virtual int32_t __stdcall get_ExtendedError(winrt::hresult*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResultFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(int32_t, winrt::hresult, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentManagerStatics
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult) GetStatus() const;
        WINRT_IMPL_AUTO(winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult) Initialize() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentManagerStatics>
    {
        template <typename D> using type = consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentManagerStatics<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentResult
    {
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentStatus) Status() const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::hresult) ExtendedError() const;
    };
    template <> struct consume<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResult>
    {
        template <typename D> using type = consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentResult<D>;
    };
    template <typename D>
    struct consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentResultFactory
    {
        WINRT_IMPL_AUTO(winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentResult) CreateInstance(winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::DeploymentStatus const& status, winrt::hresult const& extendedError) const;
    };
    template <> struct consume<winrt::Microsoft::Windows::ApplicationModel::WindowsAppRuntime::IDeploymentResultFactory>
    {
        template <typename D> using type = consume_Microsoft_Windows_ApplicationModel_WindowsAppRuntime_IDeploymentResultFactory<D>;
    };
}
#endif
