// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_Microsoft_UI_Composition_SystemBackdrops_1_H
#define WINRT_Microsoft_UI_Composition_SystemBackdrops_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.UI.Composition.SystemBackdrops.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Composition::SystemBackdrops
{
    struct __declspec(empty_bases) IDesktopAcrylicController :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDesktopAcrylicController>
    {
        IDesktopAcrylicController(std::nullptr_t = nullptr) noexcept {}
        IDesktopAcrylicController(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IDesktopAcrylicControllerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDesktopAcrylicControllerStatics>
    {
        IDesktopAcrylicControllerStatics(std::nullptr_t = nullptr) noexcept {}
        IDesktopAcrylicControllerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMicaController :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMicaController>
    {
        IMicaController(std::nullptr_t = nullptr) noexcept {}
        IMicaController(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMicaControllerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMicaControllerStatics>
    {
        IMicaControllerStatics(std::nullptr_t = nullptr) noexcept {}
        IMicaControllerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ISystemBackdropController :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISystemBackdropController>,
        impl::require<winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropController, winrt::Windows::Foundation::IClosable>
    {
        ISystemBackdropController(std::nullptr_t = nullptr) noexcept {}
        ISystemBackdropController(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
